version: '3.8'

services:
  web:
    restart: allways
    build:
      dockerfile: ./Dockerfile
      context: .
    command: gunicorn miners_online.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    env_file:
      - ./.env
  nginx:
    restart: allways
    build:
      dockerfile: ./nginx/Dockerfile
      context: .
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: