site_name: Miners Online
site_url: https://minersonline.tk
site_author: ajh123
site_description: >-
  Play our games. Use our Minecraft mods. Get some fun!
repo_url: https://github.com/ajh123-development/website
repo_name: ajh123-development/website
edit_uri: edit/main/docs/

theme:
  logo: assets/branding/favicon.svg
  favicon: assets/branding/favicon.svg
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
  static_templates:
    - authenticate.php
    - logout.php
    - profile.php
    - util.php
    - download.php
    - news/templates/include/page.php
extra_css:
- assets/stylesheets/custom.css
plugins:
  - tags:
      tags_file: About.md
  - awesome-pages
  - search
  - miners_utils
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_changes: ["404.html"]
extra:
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our site and whether users
      find what they're searching for, also to make sure you remain logged in. 
      With your consent, you're helping us to make our site better.
    actions:
      - reject
      - accept
      - manage
copyright:
  Copyright &copy; 2020 - 2022 MinersOnline
  <a href="#__consent">Change cookie settings</a>