site_name: minersonline
theme:
  name: material
  custom_dir: overrides
  static_templates:
    - authenticate.php
    - logout.php
    - profile.php
    - util.php
    - download.php
    - style.css
    - extra.css
    - news/templates/include/page.php
extra_css:
- stylesheets/extra.css
plugins:
  - search
  - miners_cli
extra_changes: ["404.html"]