site_name: minersonline
theme:
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.svg
  name: material
  custom_dir: overrides
  static_templates:
    - authenticate.php
    - logout.php
    - profile.php
    - util.php
    - download.php
    - style.css
    - extra.css
    - news/templates/include/page.php
extra_css:
- stylesheets/extra.css
plugins:
  - search
  - miners_utils
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_changes: ["404.html"]
extra:
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our site and whether users
      find what they're searching for, also to make sure you remain logged in. 
      With your consent, you're helping us to make our site better.
    actions:
      - reject
      - accept
      - manage
copyright:
  Copyright &copy; 2020 - 2022 MinersOnline
  <a href="#__consent">Change cookie settings</a>